import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'hi', 'gu', 'es', 'zh_Hant', 'ar', 'fr', 'ru', 'ja', 'de'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? guText = '',
    String? esText = '',
    String? zh_HantText = '',
    String? arText = '',
    String? frText = '',
    String? ruText = '',
    String? jaText = '',
    String? deText = '',
  }) =>
      [
        enText,
        hiText,
        guText,
        esText,
        zh_HantText,
        arText,
        frText,
        ruText,
        jaText,
        deText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Messaging
  {
    's0hj5ywl': {
      'en': 'SocialFlow Messaging',
      'ar': 'شات ميت',
      'de': 'ChatMate',
      'es': 'Compañero de chat',
      'fr': 'ChatMate',
      'gu': 'ચેટમેટ',
      'hi': 'चैटमेट',
      'ja': 'チャットメイト',
      'ru': 'ЧатМейт',
      'zh_Hant': 'ChatMate',
    },
    'gkvipqjw': {
      'en': 'Search',
      'ar': 'يبحث',
      'de': 'Suchen',
      'es': 'Buscar',
      'fr': 'Recherche',
      'gu': 'શોધો',
      'hi': 'खोज',
      'ja': '検索',
      'ru': 'Поиск',
      'zh_Hant': '搜尋',
    },
    'mhwqoyt2': {
      'en': 'Connections ',
      'ar': 'نشط الآن',
      'de': 'Jetzt aktiv',
      'es': 'Activo ahora',
      'fr': 'Actif maintenant',
      'gu': 'હમણાં સક્રિય',
      'hi': 'अभी सक्रिय',
      'ja': '現在アクティブ',
      'ru': 'Активен сейчас',
      'zh_Hant': '現在活躍',
    },
    '0jjfbca7': {
      'en': 'Recent Chats',
      'ar': 'المحادثات الأخيرة',
      'de': 'Letzte Chats',
      'es': 'Chats recientes',
      'fr': 'Discussions récentes',
      'gu': 'તાજેતરની ચેટ્સ',
      'hi': 'हाल की चैट',
      'ja': '最近のチャット',
      'ru': 'Недавние чаты',
      'zh_Hant': '最近的聊天',
    },
    'bt8hqaji': {
      'en': 'Chat',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'gu': 'ઘર',
      'hi': 'घर',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hant': '家',
    },
  },
  // edit_profile
  {
    '01okhds1': {
      'en': 'Your Name',
      'ar': 'اسمك',
      'de': 'Ihr Name',
      'es': 'Su nombre',
      'fr': 'Votre nom',
      'gu': 'તમારું નામ',
      'hi': 'आपका नाम',
      'ja': 'あなたの名前',
      'ru': 'Ваше имя',
      'zh_Hant': '您的姓名',
    },
    'eqg9e6av': {
      'en': 'Your Name',
      'ar': 'اسمك',
      'de': 'Ihr Name',
      'es': 'Su nombre',
      'fr': 'Votre nom',
      'gu': 'તમારું નામ',
      'hi': 'आपका नाम',
      'ja': 'あなたの名前',
      'ru': 'Ваше имя',
      'zh_Hant': '您的姓名',
    },
    'gdf6qs1g': {
      'en': 'Your Name',
      'ar': 'اسمك',
      'de': 'Ihr Name',
      'es': 'Su nombre',
      'fr': 'Votre nom',
      'gu': 'તમારું નામ',
      'hi': 'आपका नाम',
      'ja': 'あなたの名前',
      'ru': 'Ваше имя',
      'zh_Hant': '您的姓名',
    },
    '7y24629b': {
      'en': 'Add Your Email',
      'ar': 'أضف بريدك الإلكتروني',
      'de': 'Fügen Sie Ihre E-Mail hinzu',
      'es': 'Añade tu correo electrónico',
      'fr': 'Ajoutez votre e-mail',
      'gu': 'તમારું ઇમેઇલ ઉમેરો',
      'hi': 'अपना ईमेल जोड़ें',
      'ja': 'メールアドレスを追加',
      'ru': 'Добавьте свой адрес электронной почты',
      'zh_Hant': '新增您的電子郵件',
    },
    'k5rxqlt5': {
      'en': 'Add Your Phone number',
      'ar': 'أضف رقم هاتفك',
      'de': 'Fügen Sie Ihre Telefonnummer hinzu',
      'es': 'Añade tu número de teléfono',
      'fr': 'Ajoutez votre numéro de téléphone',
      'gu': 'તમારો ફોન નંબર ઉમેરો',
      'hi': 'अपना फ़ोन नंबर जोड़ें',
      'ja': '電話番号を追加する',
      'ru': 'Добавьте свой номер телефона',
      'zh_Hant': '新增您的電話號碼',
    },
    'qom0ubgu': {
      'en': 'Your Name is required',
      'ar': 'اسمك مطلوب',
      'de': 'Ihr Name ist erforderlich',
      'es': 'Su nombre es obligatorio',
      'fr': 'Votre nom est obligatoire',
      'gu': 'તમારું નામ જરૂરી છે',
      'hi': 'आपका नाम आवश्यक है',
      'ja': 'お名前は必須です',
      'ru': 'Ваше имя обязательно',
      'zh_Hant': '您的姓名為必填項',
    },
    'ah870gu6': {
      'en': 'Please choose an option from the dropdown',
      'ar': 'الرجاء اختيار خيار من القائمة المنسدلة',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste',
      'es': 'Por favor, elija una opción del menú desplegable.',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gu': 'કૃપા કરીને ડ્રોપડાઉનમાંથી એક વિકલ્પ પસંદ કરો.',
      'hi': 'कृपया ड्रॉपडाउन से कोई विकल्प चुनें',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ru': 'Пожалуйста, выберите вариант из выпадающего списка',
      'zh_Hant': '請從下拉式選單中選擇一個選項',
    },
    'z68vkh75': {
      'en': 'Add Your Email is required',
      'ar': 'أضف بريدك الإلكتروني مطلوب',
      'de': 'Geben Sie Ihre E-Mail-Adresse ein.',
      'es': 'Añade tu correo electrónico es requerido',
      'fr': 'Ajouter votre e-mail est obligatoire',
      'gu': 'તમારું ઇમેઇલ ઉમેરો જરૂરી છે',
      'hi': 'अपना ईमेल जोड़ना आवश्यक है',
      'ja': 'メールアドレスを入力してください',
      'ru': 'Добавьте свой адрес электронной почты. Требуется',
      'zh_Hant': '新增您的電子郵件是必需的',
    },
    'k2lwv952': {
      'en': 'Please choose an option from the dropdown',
      'ar': 'الرجاء اختيار خيار من القائمة المنسدلة',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste',
      'es': 'Por favor, elija una opción del menú desplegable.',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gu': 'કૃપા કરીને ડ્રોપડાઉનમાંથી એક વિકલ્પ પસંદ કરો.',
      'hi': 'कृपया ड्रॉपडाउन से कोई विकल्प चुनें',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ru': 'Пожалуйста, выберите вариант из выпадающего списка',
      'zh_Hant': '請從下拉式選單中選擇一個選項',
    },
    '2lgonqwu': {
      'en': 'Add Your Phone number is required',
      'ar': 'أضف رقم هاتفك مطلوب',
      'de': 'Das Hinzufügen Ihrer Telefonnummer ist erforderlich',
      'es': 'Añade tu número de teléfono es obligatorio',
      'fr': 'Ajouter votre numéro de téléphone est requis',
      'gu': 'તમારો ફોન નંબર ઉમેરો જરૂરી છે',
      'hi': 'अपना फ़ोन नंबर जोड़ना आवश्यक है',
      'ja': '電話番号の追加は必須です',
      'ru': 'Добавьте свой номер телефона. Требуется',
      'zh_Hant': '添加您的電話號碼是必需的',
    },
    'kvl46j14': {
      'en': 'Please choose an option from the dropdown',
      'ar': 'الرجاء اختيار خيار من القائمة المنسدلة',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste',
      'es': 'Por favor, elija una opción del menú desplegable.',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gu': 'કૃપા કરીને ડ્રોપડાઉનમાંથી એક વિકલ્પ પસંદ કરો.',
      'hi': 'कृपया ड्रॉपडाउन से कोई विकल्प चुनें',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ru': 'Пожалуйста, выберите вариант из выпадающего списка',
      'zh_Hant': '請從下拉式選單中選擇一個選項',
    },
    'y1zt5wcg': {
      'en': 'Save Changes',
      'ar': 'حفظ التغييرات',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Enregistrer les modifications',
      'gu': 'ફેરફારો સાચવો',
      'hi': 'परिवर्तनों को सुरक्षित करें',
      'ja': '変更を保存',
      'ru': 'Сохранить изменения',
      'zh_Hant': '儲存變更',
    },
    'y8cz92xd': {
      'en': 'Complete Your Profile',
      'ar': 'تعديل الملف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Modifier le profil',
      'gu': 'પ્રોફાઇલ સંપાદિત કરો',
      'hi': 'प्रोफ़ाइल संपादित करें',
      'ja': 'プロフィールを編集',
      'ru': 'Редактировать профиль',
      'zh_Hant': '編輯個人資料',
    },
  },
  // Profile
  {
    'rvglsewk': {
      'en': 'Edit',
      'ar': 'يحرر',
      'de': 'Bearbeiten',
      'es': 'Editar',
      'fr': 'Modifier',
      'gu': 'સંપાદિત કરો',
      'hi': 'संपादन करना',
      'ja': '編集',
      'ru': 'Редактировать',
      'zh_Hant': '編輯',
    },
    'h4liltf7': {
      'en': 'Log out',
      'ar': 'تسجيل الخروج',
      'de': 'Ausloggen',
      'es': 'Finalizar la sesión',
      'fr': 'Se déconnecter',
      'gu': 'લોગ આઉટ કરો',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hant': '登出',
    },
    'c3w08y9w': {
      'en': 'Profile',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'gu': 'પ્રોફાઇલ',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'ru': 'Профиль',
      'zh_Hant': '輪廓',
    },
  },
  // chat
  {
    '9iwaxyu2': {
      'en': 'Type something...',
      'ar': 'اكتب شيئا ما...',
      'de': 'Geben Sie etwas ein ...',
      'es': 'Escribe algo...',
      'fr': 'Tapez quelque chose...',
      'gu': 'કંઈક લખો...',
      'hi': 'कुछ लिखें...',
      'ja': '何か入力してください...',
      'ru': 'Напечатайте что-нибудь...',
      'zh_Hant': '輸入一些內容...',
    },
    '04r904z6': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'gu': 'ઘર',
      'hi': 'घर',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hant': '家',
    },
  },
  // users_screen
  {
    '3kpy6ivi': {
      'en': 'Search',
      'ar': 'يبحث',
      'de': 'Suchen',
      'es': 'Buscar',
      'fr': 'Recherche',
      'gu': 'શોધો',
      'hi': 'खोज',
      'ja': '検索',
      'ru': 'Поиск',
      'zh_Hant': '搜尋',
    },
    'twzayavs': {
      'en': 'Active Now',
      'ar': 'نشط الآن',
      'de': 'Jetzt aktiv',
      'es': 'Activo ahora',
      'fr': 'Actif maintenant',
      'gu': 'હમણાં સક્રિય',
      'hi': 'अभी सक्रिय',
      'ja': '現在アクティブ',
      'ru': 'Активен сейчас',
      'zh_Hant': '現在活躍',
    },
    '4ui83cpp': {
      'en': 'Recent Chats',
      'ar': 'المحادثات الأخيرة',
      'de': 'Letzte Chats',
      'es': 'Chats recientes',
      'fr': 'Discussions récentes',
      'gu': 'તાજેતરની ચેટ્સ',
      'hi': 'हाल की चैट',
      'ja': '最近のチャット',
      'ru': 'Недавние чаты',
      'zh_Hant': '最近的聊天',
    },
    'iyr0w54v': {
      'en': 'Users',
      'ar': 'المستخدمون',
      'de': 'Benutzer',
      'es': 'Usuarios',
      'fr': 'Utilisateurs',
      'gu': 'વપરાશકર્તાઓ',
      'hi': 'उपयोगकर्ताओं',
      'ja': 'ユーザー',
      'ru': 'Пользователи',
      'zh_Hant': '使用者',
    },
    'no8356zo': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'gu': 'ઘર',
      'hi': 'घर',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hant': '家',
    },
  },
  // onboarding
  {
    'iyn8femq': {
      'en': 'Chat Smarter, Connect Faster.',
      'ar': 'الدردشة بشكل أذكى، والتواصل بشكل أسرع.',
      'de': 'Intelligenter chatten, schneller verbinden.',
      'es': 'Chatea de forma más inteligente, conéctate más rápido.',
      'fr': 'Discutez plus intelligemment, connectez-vous plus rapidement.',
      'gu': 'વધુ સ્માર્ટ ચેટ કરો, વધુ ઝડપથી કનેક્ટ થાઓ.',
      'hi': 'स्मार्ट तरीके से चैट करें, तेजी से जुड़ें।',
      'ja': 'よりスマートにチャットして、より速く接続します。',
      'ru': 'Общайтесь умнее, общайтесь быстрее.',
      'zh_Hant': '聊天更智能，連線更快。',
    },
    '1zhs6tl8': {
      'en': 'Effortiess messaging with family and friends',
      'ar': 'تبادل الرسائل مع العائلة والأصدقاء',
      'de': 'Müheloses Versenden von Nachrichten an Familie und Freunde',
      'es': 'Mensajería sin esfuerzo con familiares y amigos',
      'fr': 'Messagerie sans effort avec la famille et les amis',
      'gu': 'પરિવાર અને મિત્રો સાથે મહેનતથી મેસેજિંગ',
      'hi': 'परिवार और दोस्तों के साथ सहज संदेश भेजना',
      'ja': '家族や友人とのEffortiessメッセージ',
      'ru': 'Трудности с обменом сообщениями с семьей и друзьями',
      'zh_Hant': '與家人和朋友輕鬆發送訊息',
    },
    'fitrbot3': {
      'en': 'Get Started',
      'ar': 'البدء',
      'de': 'Erste Schritte',
      'es': 'Empezar',
      'fr': 'Commencer',
      'gu': 'શરૂ કરો',
      'hi': 'शुरू हो जाओ',
      'ja': '始める',
      'ru': 'Начать',
      'zh_Hant': '開始',
    },
    'yi9hcmg6': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'gu': 'ઘર',
      'hi': 'घर',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hant': '家',
    },
  },
  // settings
  {
    'azjhdzhz': {
      'en': 'Edit Profile',
      'ar': 'تعديل الملف الشخصي',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Modifier le profil',
      'gu': 'પ્રોફાઇલ સંપાદિત કરો',
      'hi': 'प्रोफ़ाइल संपादित करें',
      'ja': 'プロフィールを編集',
      'ru': 'Редактировать профиль',
      'zh_Hant': '編輯個人資料',
    },
    'jfcgba25': {
      'en': 'Change theme',
      'ar': 'تغيير الموضوع',
      'de': 'Design ändern',
      'es': 'Cambiar tema',
      'fr': 'Changer de thème',
      'gu': 'થીમ બદલો',
      'hi': 'विषय को परिवर्तित करें',
      'ja': 'テーマを変更する',
      'ru': 'Изменить тему',
      'zh_Hant': '更改主題',
    },
    '40nmspdx': {
      'en': 'Logout',
      'ar': 'تسجيل الخروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Déconnexion',
      'gu': 'લોગઆઉટ',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hant': '登出',
    },
    '6z67djfi': {
      'en': 'Delete Account',
      'ar': 'تسجيل الخروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Déconnexion',
      'gu': 'લોગઆઉટ',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hant': '登出',
    },
    'ei583ca7': {
      'en': 'Settings',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Myprofile
  {
    'opct7294': {
      'en': 'posts',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'i4fj0na5': {
      'en': 'followers',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'nqp74iji': {
      'en': 'following',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'u7ctn7ho': {
      'en': '@',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'faagj4e7': {
      'en': 'Bio',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'w1md5vwp': {
      'en': 'Social Posts',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '7b3owck8': {
      'en': 'Posts',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '3hy1pwrm': {
      'en': 'Profile',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // otherprofilePage
  {
    't9gb2azd': {
      'en': 'posts',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'r3a6j2pn': {
      'en': 'followers',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'cj3y7pqp': {
      'en': 'following',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'pkdtxgq2': {
      'en': '@',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'wc2s8jiw': {
      'en': 'Bio',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'pmfo5yi4': {
      'en': 'Unfollow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vgx99xff': {
      'en': 'Follow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'rilfr63w': {
      'en': 'Social Posts',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '21h6vcu1': {
      'en': 'Posts',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xnn394ce': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // search
  {
    'qppopt9w': {
      'en': 'Search for Users...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'nnrd010o': {
      'en': 'Users matching search',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'j764gevv': {
      'en': 'Users',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'mrqv98is': {
      'en': 'Search',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // followerslitotheruser
  {
    'rmvfbe4a': {
      'en': 'Unfollow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'r2p52k9i': {
      'en': 'Follow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'alkeccal': {
      'en': 'Followers',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'tgzi4hcp': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // FollowingListotheruser
  {
    'bjls73sk': {
      'en': 'Unfollow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'dcbe84b0': {
      'en': 'Follow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bdv0oxjz': {
      'en': 'Following',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xwlvb0kr': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // FollowingListAuthUser
  {
    'su4jxijh': {
      'en': 'Unfollow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'x5w2zkni': {
      'en': 'Follow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'zz0y1f5g': {
      'en': 'Following',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'tcxah3l0': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // followerlistFromauth
  {
    '5uowe4n7': {
      'en': 'Unfollow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xl65qpqf': {
      'en': 'Follow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '08yvzcyb': {
      'en': 'Followers',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'e1a9tv5u': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // feed
  {
    'm7vss4wa': {
      'en': 'SociaFlow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vgulewz1': {
      'en': 'Chat With Flow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    's1oie63o': {
      'en': 'feed',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // NewPost
  {
    'kvje9iik': {
      'en': 'Whats On your Mind....',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'wolunxsj': {
      'en': 'Post',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ffj5r2zr': {
      'en': 'New Post',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '7dq3kxbc': {
      'en': 'New Post',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // chatCopy
  {
    'fnrm15el': {
      'en': 'Type something...',
      'ar': 'اكتب شيئا ما...',
      'de': 'Geben Sie etwas ein ...',
      'es': 'Escribe algo...',
      'fr': 'Tapez quelque chose...',
      'gu': 'કંઈક લખો...',
      'hi': 'कुछ लिखें...',
      'ja': '何か入力してください...',
      'ru': 'Напечатайте что-нибудь...',
      'zh_Hant': '輸入一些內容...',
    },
    'o8ncw1uy': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'gu': 'ઘર',
      'hi': 'घर',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hant': '家',
    },
  },
  // Auth3
  {
    '53s8d77d': {
      'en': 'SocialFlow',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'dffmp0cu': {
      'en': 'Create Account',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'm948f5ok': {
      'en': 'Create Account',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'cmp5pm2e': {
      'en': 'Let\'s get started by filling out the form below.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'qv57mupc': {
      'en': 'Email',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'pxqqciyv': {
      'en': 'Name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2w74kydv': {
      'en': 'Password',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'cl352w9c': {
      'en': 'Password',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ogy0i9aq': {
      'en': 'Get Started',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '9z7rrlax': {
      'en': 'Or sign up with',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'alrgb407': {
      'en': 'Continue with Google',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '479w878d': {
      'en': 'Continue with Apple',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'cpdutnb5': {
      'en': 'Log In',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '6hlu68ir': {
      'en': 'Welcome Back',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'for7natn': {
      'en': 'Fill out the information below in order to access your account.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2972mc3t': {
      'en': 'Email',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'w04xyb1u': {
      'en': 'Password',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ewismktt': {
      'en': 'Sign In',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'okq9iik1': {
      'en': 'Or sign in with',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'i4z9nfb5': {
      'en': 'Continue with Google',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vdp4kbmc': {
      'en': 'Continue with Apple',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'kb52ktfx': {
      'en': 'Forgot Password?',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '3bpqi977': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Flow
  {
    'h4nct3xm': {
      'en': 'Flow Ai',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'efrlmnqs': {
      'en': 'Ask Flow Anything...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '6cy6tu4l': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // deleteAccount
  {
    'hq923081': {
      'en': 'Are you sure you want\nto Delete your account?',
      'ar': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'de': 'Möchten Sie sich wirklich abmelden?',
      'es': '¿Estás seguro que deseas cerrar sesión?',
      'fr': 'Êtes-vous sûr de vouloir\nvous déconnecter ?',
      'gu': 'શું તમે ખરેખર લોગ આઉટ કરવા માંગો છો?',
      'hi': 'क्या आप लॉग आउट करना चाहते हैं?',
      'ja': '本当にログアウトしますか？',
      'ru': 'Вы уверены, что хотите выйти?',
      'zh_Hant': '你確定要\n退出？',
    },
    'okyucvut': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'gu': 'રદ કરો',
      'hi': 'रद्द करना',
      'ja': 'キャンセル',
      'ru': 'Отмена',
      'zh_Hant': '取消',
    },
    'u31yjxrx': {
      'en': 'Delete',
      'ar': 'تسجيل الخروج',
      'de': 'Abmelden',
      'es': 'Finalizar la sesión',
      'fr': 'Se déconnecter',
      'gu': 'લોગ આઉટ',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hant': '登出',
    },
  },
  // logOut
  {
    'yql69eut': {
      'en': 'Are you sure you want\nto log out?',
      'ar': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'de': 'Möchten Sie sich wirklich abmelden?',
      'es': '¿Estás seguro que deseas cerrar sesión?',
      'fr': 'Êtes-vous sûr de vouloir\nvous déconnecter ?',
      'gu': 'શું તમે ખરેખર લોગ આઉટ કરવા માંગો છો?',
      'hi': 'क्या आप लॉग आउट करना चाहते हैं?',
      'ja': '本当にログアウトしますか？',
      'ru': 'Вы уверены, что хотите выйти?',
      'zh_Hant': '你確定要\n退出？',
    },
    't0g810u7': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'gu': 'રદ કરો',
      'hi': 'रद्द करना',
      'ja': 'キャンセル',
      'ru': 'Отмена',
      'zh_Hant': '取消',
    },
    'jxt6iyem': {
      'en': 'Log Out',
      'ar': 'تسجيل الخروج',
      'de': 'Abmelden',
      'es': 'Finalizar la sesión',
      'fr': 'Se déconnecter',
      'gu': 'લોગ આઉટ',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hant': '登出',
    },
  },
  // more
  {
    '5swygwvz': {
      'en': 'Delete Chat',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'yotsd7mf': {
      'en': 'Block User',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // MaterialMessage
  {
    'wsitkyio': {
      'en': 'Block User',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Comments
  {
    'dae4nw79': {
      'en': 'Comments',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'l8b0rd7v': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'idsnmchn': {
      'en': 'Comment....',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Deleteaction
  {
    'urmbjsmk': {
      'en': 'Delete',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1uanqbtv': {
      'en': 'Cancel',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Miscellaneous
  {
    '5wajhq5p': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ebv7wgq3': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'no9si425': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'dmw2ewet': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bomziphd': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'zlulrwge': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'lpp6otpe': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'em86ccgu': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'o0r1zeoz': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'em92rzvb': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'rgm8urca': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'pshwtjam': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2433bgkv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ap09bqp9': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'w6u2zmbo': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'y8f5z1zo': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'jv30bwbn': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'r4wxy21l': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1ecvzfng': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'qhrn3ugq': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'teh3xl7a': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '685fay6p': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1y7qy7ew': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'tyzxfdfy': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'yly22bw2': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '0mdowe7b': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vyba20tv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
